In [ ]:
# ques1 1. What is a Python library? Why ^o we use Python libraries?
 Ans: A collection of modules that are linked together it carry bundles of codes  that can be used in the different codes its save time for the developers and time also they have not right
        the same code on the regular basis for the same things

In [ ]:
## Ques2 What is the difference between Numpy array and List?
Ans: if we working on the numerical data and in which it require efficient computation and memory usage then the numpy aaray is the best
    choice if we have to work on the general purpose when deal with the heterogenous data than python lists are more flexibillity

In [ ]:
# ques3 3. Find the shape, size and dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [10]:
# Answer 3
import numpy as np # here we import numpy for the calculation
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

# Print the shape, size, and dimension of the array
print("Shape:", a.shape)
print("Size:", a.size)
print("Dimension:", a.ndim)

Shape: (3, 4)
Size: 12
Dimension: 2


In [ ]:
# Ques4: 4. Write python code to access the first row of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [15]:
#Ans4
a=np.array([[1,2,3,4],
          [5,6,7,8,],
          [9,10,11,12]])
first_row=a[0] # [0] beacuse the index of all the element are present at the 0 
print("first_row",first_row)# here print statment is used to print the answer

first_row [1 2 3 4]


In [ ]:
# Ques5. How do you access the element at the third row and fourth column from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [16]:
# ans5
a=np.array([[1,2,3,4],
          [5,6,7,8,],
          [9,10,11,12]])
# access the element at the 3rd row(index 2) and 4th row index(3)
element=a[2,3]
print("element at the 3rd row and 4th column",element)


element at the 3rd row and 4th column 12


In [ ]:
# Ques 6.. Write code to extract all odd-indexed elements from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [19]:
# ans 6
import numpy as np

# Define the 2D array as a NumPy array
a = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

# Extract all odd-indexed elements using slicing
odd_indexed_elements = a[:, 1::2]

# Print the extracted odd-indexed elements
print("Odd-indexed elements:")
print(odd_indexed_elements)


Odd-indexed elements:
[[ 2  4]
 [ 6  8]
 [10 12]]


In [22]:
# Ques 7:. How can you generate a random 3x3 matrix with values between 0 and1?

df=np.random.rand(3,3) # we use rnadom.rand for the random values that we want 

print("matrix of 3*3",df) # here we use print statment here


matrix of 3*3 [[0.97944588 0.83903116 0.24935867]
 [0.7870313  0.68197077 0.04651178]
 [0.55015334 0.49473267 0.68118197]]


In [ ]:
# ques 8:  Describe the difference between np.random.rand and np.random.randn?
random. rand() produces random numbers from a uniform distribution over the interval [0, 1), while np. random. randn() generates random numbers from a standard normal distribution

In [ ]:
# ques 9. Write code to increase the dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [24]:
# ans 9


# Define the 2D array
a = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

# Increase the dimension of the array to 3D by adding a new axis
expanded_array = np.expand_dims(a, axis=0)

# Print the original and expanded arrays
print("Original 2D Array:")
print(a)
print("\nExpanded 3D Array:")
print(expanded_array)



Original 2D Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Expanded 3D Array:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


In [ ]:
# ques 10:  How to transpose the following array in NumPy?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [29]:
# Ans10
a = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

# Transpose the array
transposed_a = a.T

# Print the original and transposed arrays
print("Original Array:")
print(a)
print("\nTransposed Array:")
print(transposed_a)


Original Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Transposed Array:
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [ ]:
# ques 11. 11. Consi^der the following matrix:
Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
Perform the following operation using Python


In [30]:
 # ans11 
# 1 index wise


# Define matrix A2 and B2
A2 = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

B2 = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

# Perform index-wise multiplication (element-wise multiplication)
index_wise_multiplication = A2 * B2

# Print the result
print("Index-wise Multiplication (Element-wise multiplication):\n", index_wise_multiplication)


Index-wise Multiplication (Element-wise multiplication):
 [[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]


In [33]:
# ans 11 part 2
import numpy as np

# Define matrix A2 and transposed B2
A2 = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

# Transpose matrix B2
B2_transposed = np.array([
    [1, 5, 9],
    [2, 6, 10],
    [3, 7, 11],
    [4, 8, 12]
])

# Perform matrix multiplication (A2 @ B2_transposed)
matrix_multiplication = np.matmul(A2, B2_transposed)

# Print the result of matrix multiplication
print("Matrix Multiplication (A2 @ B2_transposed):\n", matrix_multiplication)


Matrix Multiplication (A2 @ B2_transposed):
 [[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]


In [34]:
# ans 11 part 3
import numpy as np

# Define matrix A2 and B2
A2 = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

B2 = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

# Perform matrix addition (element-wise addition)
matrix_addition = A2 + B2

# Print the result of matrix addition
print("Matrix Addition (A2 + B2):\n", matrix_addition)


Matrix Addition (A2 + B2):
 [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]


In [35]:
# ans 11 part 4 
import numpy as np

# Define matrix A2 and B2
A2 = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

B2 = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

# Perform matrix subtraction (element-wise subtraction)
matrix_subtraction = A2 - B2

# Print the result of matrix subtraction
print("Matrix Subtraction (A2 - B2):\n", matrix_subtraction)


Matrix Subtraction (A2 - B2):
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [36]:
# Ques12. Which function in Numpy can be used to swap the byte order of an array?



In [37]:
# Ans: import numpy as np

# Create a numpy array with big-endian byte order
arr = np.array([1, 256, 8755], dtype=np.int16).newbyteorder()

# Swap the byte order of the array
arr = arr.byteswap()

# Print the array
print(arr)

[   1  256 8755]


In [ ]:
#Ques13.What is the significance of the np.linalg.inv function?

In [38]:
#ans13
import numpy as np

# Define a square matrix
A = np.array([[1, 2], [3, 4]])

# Compute the inverse of the matrix
A_inv = np.linalg.inv(A)

# Print the original matrix and its inverse
print("Original matrix:")
print(A)
print("\nInverse of the matrix:")
print(A_inv)

Original matrix:
[[1 2]
 [3 4]]

Inverse of the matrix:
[[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
#ques13 What does the np.reshape function do, and how is it used?

In [41]:
#ans13 
import numpy as np

# Create a NumPy array
arr = np.array([1, 2, 3, 4, 5, 6])

# Reshape the array into a 2x3 matrix
reshaped_arr = np.reshape(arr, (2, 3))

print(reshaped_arr)
#
#The np.reshape function in NumPy is used to change the shape (dimensions) of an array without changing its data. This function does not modify the original array, but instead, it returns a new array with the specified shape.

[[1 2 3]
 [4 5 6]]


In [ ]:
#Ques 15: 
#What is broadcasting in Numpy

# ans 
Broadcasting in NumPy is a powerful mechanism that allows NumPy to perform operations on arrays of different shapes, which can greatly simplify the syntax and execution of various numerical computations.

The key idea behind broadcasting is that when performing element-wise operations between arrays, NumPy automatically adjusts the dimensions of the arrays to make the operation possible, rather than requiring the arrays to have exactly the same shape.